### ISSUE TITLE
A question about out of memory sampling

### ISSUE THREAD

**Issue by soodoshll** [concept-inversion/C-SAW#1]
Hi, I have one question about out of memory sampling. When we do layer-wise sampling, we need the information of the whole frontier. How it is implemented in C-SAW? Thank you!

**Comment by concept-inversion** [comment]
Hi Qidong Su.
Thank you for your interest in C-SAW.
Yes. The frontier queue can be in different depths and the sampling for the
previous layer should be completed for sampling the next layer. The current
C-SAW implementation does not support layer-wise sampling for out of memory
sampling as naive implementation of layer-sampling would be inefficient. I
am working on efficient implementation of layer sampling for out of memory.

**Comment by soodoshll** [comment]
Thank you for your reply!
