### ISSUE TITLE
Complie error for stream version

### ISSUE THREAD

**Issue by gpzlx1** [concept-inversion/C-SAW#5]
`stream` version cannot be complied. An inconsistent interface causes it.
In `main_entry.cpp`, it calls
```c++
    Sampler(char*, char*, int, int, int, int, int, int, arguments, int)
```
However, in `streaming_sampling.cu`, it is defined
```c++
    Sampler(char*, char*, int, int, int, int, int, arguments, int)
```
where lacks of `depth` argument.

It's not difficult to fix it. Just move the local variable `depth` to the function parameter list. 
Thx. Best wishes to you.

**Comment by concept-inversion** [comment]
Thanks a lot. Saved me some time. :D
