### ISSUE TITLE
Regarding New Streaming Version

### ISSUE THREAD

**Issue by spapadias** [concept-inversion/C-SAW#6]
Hello,

As far as I am concerned the initial C-Saw version (in the paper at least) did not consider the streaming setting. 
Is there a manuscript to read about your extension for streaming?

Based on this..._"This repo contains two folders. One for streaming sampling for large graph and another for non-streaming sampling for graphs that fit in GPU memory."_...I guess you mean that you "stream the graph" little by little in the GPU. So it is not "stream processing". Am I wrong?

Thanks in advance.

Best,
Makis

**Comment by concept-inversion** [comment]
Hi Makis, 
You are right. For large graph, we divide the graph into N partitions. For sampling, we copy one or multiple partitions to GPU using CUDA streams at a time which have active vertices to sample. That's the "streaming" version of C-SAW. I will update the README/change the name for clarifying that. 
 
The recent updates in the repo are just some changes and fixes, not any extension. 

Regards,
Santosh
